### ISSUE TITLE
"Download All of My Metadata" in submission dashboard not uptodate 

### ISSUE THREAD

**Issue by xzhuo** [target2/SubmissionSystem#37]
It does not get all the metadata in PROD database;
It does not use the latest template (3.0.0 today).

**Comment by epehrsson** [comment]
I think current version is 3.0.4. Should we combine this with Issue #32 ?

**Comment by debugpoint136** [comment]
@xzhuo with 3.0.4 update

```Traceback (most recent call last):
  File "populate_metadata_Excel.py", line 113, in <module>
    main()
  File "populate_metadata_Excel.py", line 108, in main
    reader.write_book_header(workbook)
  File "/home/dpuru/TargetBulkUpload/sheetreader.py", line 105, in write_book_header
    if column_dict['values_restricted']:  # Drop-down with restricted values
KeyError: 'values_restricted'```

**Comment by xzhuo** [comment]
Fixed the value_restricted bug!

**Comment by debugpoint136** [comment]
Fixed and deployed. @xzhuo  Please test and close this.

**Comment by xzhuo** [comment]
It is pulling the latest template and latest metadata. but why the tabs are not sorted?

**Comment by debugpoint136** [comment]
Do you have any suggestions how to debug?

**Comment by xzhuo** [comment]
"Download all my metadata" works as expected, but "download empty template" still not in order.

**Comment by xzhuo** [comment]
It is all good now, close it.
